
language: go

go:
  - 1.5
  
before_script:
- sudo add-apt-repository ppa:masterminds/glide && sudo apt-get update
- sudo apt-get install glide

script:
- glide get github.com/Masterminds/cookoo 
- glide install
- go build
- glide up

